### PR TITLE
SymbolRow design improvements

### PR DESCRIPTION
**Pull request by aimproxy**
Hi owners, this is my first PR for this project, please be nice ahahaha.
I just made some changes I thought it looks better with them, please see above the differences.
I will wait for feedback. 

Markets

Visibility issues:
- [x] Make labels bold

Design Improvements:
- [x] Disengage change from percent change
Ps: Looks more cleaner this away

Thx

### CODE REVIEW

**Comment by tomasz-oponowicz** [comment]
@aimproxy Thanks for your contribution. Let me postpone it a bit. We are preparing mockups for new features. Maybe we will adjust this view too. To be continued...

**Comment by aimproxy** [comment]
I will suggest implement a watchlist to separate stocks. I wish I could help with the project, I found it very interesting!

**Comment by tomasz-oponowicz** [comment]
> I will suggest implement a watchlist to separate stocks.

Can you elaborate? Do you mean grouping?

> I wish I could help with the project, I found it very interesting!

Welcome on board! :) I would love to have some help. 

I would like to suggest #6. The idea is to add reordering capability in the edit mode. Drag and drop should be possible so one can reorder the list on mobile. I have never done it before but I think there is a stock widget for this functionality. 

Does it work for you?

**Comment by aimproxy** [comment]
> Can you elaborate? Do you mean grouping?

Well you can imagine this like a **Pie** on Trading 212 or a watch list on yahoo finance app.
There is the link for Trading 212: https://helpcentre.trading212.com/hc/en-us/articles/360009313957-Pies-AutoInvest-Introduction

> I would like to suggest #6. The idea is to add reordering capability in the edit mode.
I went to see the gnome settings files and opened the `cc-search-panel-row.ui ` file, so what I found is just a **GtkListBox** that contains a `GtkEventBox` called drag_handle.

In the code, Gnome Settings uses Drag an Drop system, here the link: https://developer.gnome.org/gtk3/stable/gtk3-Drag-and-Drop.html

I look into it more deeply Monday...

**Comment by tomasz-oponowicz** [comment]
Solved by #46 and #56

**Pull request closed without merging**
